django/chat/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import include, path
from django.utils.html import format_html

from . import responses, views

app_name = "chat"


urlpatterns = [
    path("", views.new_chat, name="new_chat"),
    path("chat-with-ai/", views.new_chat_with_ai, name="chat_with_ai"),
    path("summarize/", views.new_summarize, name="summarize"),
    path("translate/", views.new_translate, name="translate"),
    path("qa/", views.new_qa, name="qa"),
    path("document-qa/", views.new_document_qa, name="document_qa"),
    path("id/<str:chat_id>/", views.chat, name="chat"),
    path("id/<str:chat_id>/upload", views.save_upload, name="upload"),
    path(
        "id/<str:chat_id>/download_glossary/",
        views.download_glossary,
        name="download_glossary",
    ),
    path(
        "id/<str:chat_id>/delete/<str:current_chat>",
        views.delete_chat,
        name="delete_chat",
    ),
    path("delete_all_chats/", views.delete_all_chats, name="delete_all_chats"),
    path("id/<str:chat_id>/message/", views.chat_message, name="chat_message"),
    path(
        "message/<int:message_id>/delete/", views.delete_message, name="delete_message"
    ),
    path(
        "message/<int:message_id>/response/",
        responses.otto_response,
        name="chat_response",
    ),
    path(
        "message/<int:message_id>/response/stop/",
        responses.stop_response,
        name="stop_response",
    ),
    path(
        "message/<int:message_id>/response/cost_warning/",
        views.cost_warning,
        name="cost_warning",
    ),
    path(
        "message/<int:message_id>/sources/",
        views.message_sources,
        name="message_sources",
    ),
    path(
        "message/<int:message_id>/sources/highlight/",
        views.message_sources,  # same view, but highlight will be read from query params
        name="message_sources_highlight",
    ),
    path("file/<int:file_id>/", views.download_file, name="download_file"),
    path(
        "thumbs-feedback/<int:message_id>/<str:feedback>",
        views.thumbs_feedback,
        name="thumbs_feedback",
    ),
    path("id/<str:chat_id>/options/", views.chat_options, name="chat_options"),
    path(
        "id/<str:chat_id>/options/preset/<str:action>",
        views.chat_options,
        name="chat_options",
    ),
    path(
        "id/<str:chat_id>/options/preset/<str:action>/<str:preset_id>",
        views.chat_options,
        name="chat_options",
    ),
    path(
        "id/<str:chat_id>/options/set_qa_library/<int:library_id>",
        views.update_qa_options_from_librarian,
        name="update_from_librarian",
    ),
    path(
        "id/<str:current_chat_id>/rename/<str:chat_id>/",
        views.rename_chat,
        name="rename_chat",
    ),
    path(
        "id/<str:chat_id>/share/",
        views.share_chat,
        name="share_chat",
    ),
    path(
        "id/<str:current_chat_id>/list_item/<str:chat_id>",
        views.chat_list_item,
        name="chat_list_item",
    ),
    path(
        "id/<str:chat_id>/options/presets/",
        views.get_presets,
        name="get_presets",
    ),
    path(
        "id/<str:chat_id>/options/presets/<str:preset_id>/edit/",
        views.edit_preset,
        name="edit_preset",
    ),
    path(
        "id/<str:chat_id>/options/presets/save_options/",
        views.save_preset,
        name="save_preset",
    ),
    path(
        "id/<str:chat_id>/options/presets/form/",
        views.open_preset_form,
        name="open_preset_form",
    ),
    path(
        "presets/<int:preset_id>/default/<str:chat_id>",
        views.set_preset_default,
        name="set_preset_default",
    ),
    path("generate-prompt/", views.generate_prompt_view, name="generate_prompt_view"),
    path("id/<str:chat_id>/email_author/", views.email_author, name="email_author"),
    path(
        "id/<str:current_chat_id>/pin_chat/<str:chat_id>/",
        views.pin_chat,
        name="pin_chat",
    ),
    path(
        "id/<str:current_chat_id>/unpin_chat/<str:chat_id>/",
        views.unpin_chat,
        name="unpin_chat",
    ),
    path("search/", views.search_chats, name="search_chats"),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

django/chronology_email/urls.py
from django.urls import path

from . import views

app_name = "chronology_email"

urlpatterns = [
    path("", views.upload_emails, name="index"),
    path("delete_email/<int:email_id>/", views.delete_email, name="delete_email"),
    path(
        "add_emails_to_thread/<uuid:thread_id>/",
        views.add_emails_to_thread,
        name="add_emails_to_thread",
    ),
    path("delete_thread/<uuid:thread_id>/", views.delete_thread, name="delete_thread"),
]

django/otto/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import include, path, re_path
from django.views import defaults as default_views

from autocomplete import HTMXAutoComplete
from azure_auth.views import azure_auth_callback

from . import views

urlpatterns = [
    path("healthz/", views.health_check, name="health_check"),
    path("", views.index, name="index"),
    re_path(r"^upload/", include("django_file_form.urls")),
    path("welcome/", views.welcome, name="welcome"),
    # AC-2: Entra Integration Helper App Configuration
    # AC-14: Login Page Accessibility
    path("azure_auth/login", views.login, name="login"),
    path("azure_auth/", include("azure_auth.urls")),
    path("accounts/login/callback/", azure_auth_callback, name="callback"),
    # path("admin/", admin.site.urls), # Do not expose the admin site in production
    path("librarian/", include("librarian.urls")),
    path("laws/", include("laws.urls")),
    path("text_extractor/", include("text_extractor.urls")),
    path("manage_banner/", views.manage_banner, name="manage_banner"),
    path("user_management/", views.manage_users, name="manage_users"),
    path("user_management/form/", views.manage_users_form, name="manage_users_form"),
    path(
        "user_management/form/<user_id>/",
        views.manage_users_form,
        name="manage_users_form",
    ),
    path(
        "user_management/form/<str:user_ids>/",
        views.manage_users_form,
        name="manage_users_form",
    ),
    path("user_management/upload/", views.manage_users_upload, name="upload_users"),
    path(
        "user_management/download/", views.manage_users_download, name="download_users"
    ),
    path("user_management/pilots/", views.manage_pilots, name="manage_pilots"),
    path(
        "user_management/pilots/form/",
        views.manage_pilots_form,
        name="manage_pilots_form",
    ),
    path(
        "user_management/pilots/form/<pilot_id>/",
        views.manage_pilots_form,
        name="manage_pilots_form",
    ),
    path("user_management/costs/", views.cost_dashboard, name="cost_dashboard"),
    path("load_test/enable", views.enable_load_testing, name="enable_load_testing"),
    path("load_test/disable", views.disable_load_testing, name="disable_load_testing"),
    path("load_test/", views.load_test, name="load_test"),
    path("user_cost/", views.user_cost, name="user_cost"),
    path("extend_session/", views.extend_session, name="extend_session"),
    path("terms_of_use/", views.terms_of_use, name="terms_of_use"),
    path(
        "frequently_asked_questions/",
        views.frequently_asked_questions,
        name="frequently_asked_questions",
    ),
    path(
        "user_management/mark_tour_completed/<str:tour_name>/",
        views.mark_tour_completed,
        name="mark_tour_completed",
    ),
    path(
        "user_management/reset_completion_flags/",
        views.reset_completion_flags,
        name="reset_completion_flags",
    ),
    path("feedback/", views.feedback_message, name="user_feedback"),
    path("feedback/<int:message_id>/", views.feedback_message, name="user_feedback"),
    path(
        "user_management/feedback", views.feedback_dashboard, name="feedback_dashboard"
    ),
    path(
        "user_management/feedback/<int:page_number>",
        views.feedback_dashboard,
        name="feedback_dashboard",
    ),
    path("user_management/feedback/list", views.feedback_list, name="feedback_list"),
    path(
        "user_management/feedback/list/<int:page_number>",
        views.feedback_list,
        name="feedback_list",
    ),
    path("user_management/feedback/stats", views.feedback_stats, name="feedback_stats"),
    path(
        "user_management/feedback/<int:feedback_id>/<str:form_type>",
        views.feedback_dashboard_update,
        name="feedback_dashboard_update",
    ),
    path(
        "user_management/feedback/download",
        views.feedback_download,
        name="feedback_download",
    ),
    path("user_management/blocked_urls", views.list_blocked_urls, name="blocked_urls"),
    path(
        "notifications/<int:notification_id>/", views.notification, name="notification"
    ),
    path("notifications/", views.notifications, name="notifications"),
    path("i18n/", include("django.conf.urls.i18n")),
    path("chat/", include("chat.urls")),
    # exposes /metrics endpoint, accessible by anonymous users, restricted by ip addresses. See metrics/web.config and IIS's IP Address and Domain Restrictions
    path("", include("django_prometheus.urls")),
    *HTMXAutoComplete.url_dispatcher("ac"),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if settings.DEBUG_TOOLBAR:
    urlpatterns.append(
        path("__debug__/", include("debug_toolbar.urls")),
    )

if settings.DEBUG:
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page Not Found")},
        ),
        path("500/", default_views.server_error),
    ]

django/chronology_email/models.py
import uuid

from django.db import models


class Email(models.Model):
    file = models.FileField(upload_to="emails/", null=True, blank=True)
    sender = models.CharField(max_length=255)
    receiver = models.CharField(max_length=255)
    sent_date = models.DateTimeField(null=True, blank=True)
    preview_text = models.TextField(null=True, blank=True)
    thread_id = models.UUIDField()
    attachment_count = models.IntegerField(default=0)  # New field for attachments

    def __str__(self):
        return f"{self.sender} to {self.receiver} on {self.sent_date}"


class Thread(models.Model):
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"Thread {self.id}"

django/chronology_email/views.py
import uuid

from django.db.models import Count, Max, Q, Sum
from django.shortcuts import get_object_or_404, redirect, render

from .forms import EmailUploadForm
from .models import Email
from .utils import extract_email_details, summary


def upload_emails(request):
    email_instances = []
    thread_id = uuid.uuid4()

    if request.method == "POST":
        form = EmailUploadForm(request.POST, request.FILES)
        if form.is_valid():
            uploaded_files = request.FILES.getlist("email_files")

            for file in uploaded_files:
                email_instance = Email(file=file, thread_id=thread_id)
                email_details = extract_email_details(file)
                email_instance.sender = email_details.get("sender")
                email_instance.receiver = email_details.get("receiver")
                email_instance.sent_date = email_details.get("sent_date")
                email_instance.preview_text = email_details.get("preview_context")
                email_instance.attachment_count = email_details.get(
                    "attachment_count", 0
                )

                if email_instance.sent_date:
                    email_instance.save()
                    email_instances.append(email_instance)
    else:
        form = EmailUploadForm()

    threads = (
        Email.objects.values("thread_id")
        .annotate(
            total_emails=Count("id"),
            unique_participants=Count("sender", distinct=True)
            + Count("receiver", distinct=True),
            total_attachments=Sum("attachment_count"),
            last_email_date=Max("sent_date"),
        )
        .distinct()
    )

    emails_by_thread = {
        thread["thread_id"]: {
            "emails": Email.objects.filter(thread_id=thread["thread_id"]).order_by(
                "-sent_date"
            ),
            "total_emails": thread["total_emails"],
            "unique_participants": thread["unique_participants"],
            "total_attachments": thread["total_attachments"],
            "last_email_date": thread["last_email_date"],
            "thread_summary": summarize_thread(thread["thread_id"]),
        }
        for thread in threads
    }

    return render(
        request, "upload.html", {"form": form, "emails_by_thread": emails_by_thread}
    )


def add_emails_to_thread(request, thread_id):
    if request.method == "POST":
        form = EmailUploadForm(request.POST, request.FILES)
        if form.is_valid():
            uploaded_files = request.FILES.getlist("msg_files")

            for file in uploaded_files:
                email_instance = Email(thread_id=thread_id, file=file)
                email_details = extract_email_details(file)
                email_instance.sender = email_details.get("sender")
                email_instance.receiver = email_details.get("receiver")
                email_instance.sent_date = email_details.get("sent_date")
                email_instance.preview_text = email_details.get("preview_context")
                email_instance.attachment_count = email_details.get(
                    "attachment_count", 0
                )
                email_instance.save()

    return redirect("chronology_email:index")


def delete_email(request, email_id):
    if request.method == "POST":
        email = get_object_or_404(Email, id=email_id)
        email.delete()
    return redirect("chronology_email:index")


def delete_thread(request, thread_id):
    if request.method == "POST":
        Email.objects.filter(thread_id=thread_id).delete()
    return redirect("chronology_email:index")


def summarize_thread(thread_id):
    emails = Email.objects.filter(thread_id=thread_id)
    combined_text = " ".join(
        email.preview_text for email in emails if email.preview_text
    )
    return summary(combined_text)

django/chronology_email/templates/upload.html
{% extends 'base.html' %}
{% load i18n %}

{% block page_title %}
  {% trans "Upload Emails" %}
{% endblock %}

{% block content_container %}
  <div class="container mt-4">
    <h2>{% trans "Upload .msg Files" %}</h2>

    <form method="post" enctype="multipart/form-data">
      {% csrf_token %}
      {{ form.as_p }}
      <button type="submit" class="btn btn-primary">New Thread</button>
    </form>

    {% if emails_by_thread %}
      <h3>Email Threads</h3>
      <div>
        {% for thread_id, thread_data in emails_by_thread.items %}
          <div class="card my-3">
            <div class="card-header">
              <p>
                <strong>Summary:</strong> {{ thread_data.thread_summary }}
              </p>
              <div style="display: flex;
                          justify-content: space-between;
                          align-items: center">
                <div>
                  <p>
                    <strong>Total Emails:</strong> {{ thread_data.total_emails }}
                  </p>
                  <p>
                    <strong>Unique Participants:</strong> {{ thread_data.unique_participants }}
                  </p>
                </div>
                <div>
                  <p>
                    <strong>Total Attachments:</strong> {{ thread_data.total_attachments }}
                  </p>
                  <p>
                    <strong>Last Email Date:</strong> {{ thread_data.last_email_date }}
                  </p>
                </div>
                <div>
                  <button onclick="toggleThread('{{ thread_id }}')" class="btn btn-link p-0">
                    <span id="toggle-icon-{{ thread_id }}">▼</span>
                  </button>
                  <button onclick="toggleUploadForm('{{ thread_id }}')"
                          class="btn btn-primary btn-sm">+</button>
                  <form action="{% url 'chronology_email:delete_thread' thread_id=thread_id %}"
                        method="post"
                        style="display:inline">
                    {% csrf_token %}
                    <button type="submit" class="btn btn-danger btn-sm">-</button>
                  </form>
                </div>
              </div>
              <form id="upload-form-{{ thread_id }}"
                    action="{% url 'chronology_email:add_emails_to_thread' thread_id=thread_id %}"
                    method="post"
                    enctype="multipart/form-data"
                    style="display: none;
                           margin-top: 10px">
                {% csrf_token %}
                <label for="msg-files-{{ thread_id }}">Add .msg Files:</label>
                <input type="file"
                       name="msg_files"
                       id="msg-files-{{ thread_id }}"
                       multiple
                       required>
                <button type="submit" class="btn btn-success btn-sm">Upload</button>
              </form>
            </div>
            <div id="thread-{{ thread_id }}" class="card-body" style="display:none;">
              <table class="table table-striped">
                <thead>
                  <tr>
                    <th>Sender</th>
                    <th>Receiver</th>
                    <th>Sent Date</th>
                    <th>Preview</th>
                    <th>Action</th>
                  </tr>
                </thead>
                <tbody>
                  {% for email in thread_data.emails %}
                    <tr>
                      <td>{{ email.sender }}</td>
                      <td>{{ email.receiver }}</td>
                      <td>{{ email.sent_date }}</td>
                      <td>{{ email.preview_text }}</td>
                      <td>
                        <form action="{% url 'chronology_email:delete_email' email.id %}"
                              method="post"
                              style="display:inline">
                          {% csrf_token %}
                          <button type="submit" class="btn btn-danger btn-sm">X</button>
                        </form>
                      </td>
                    </tr>
                  {% endfor %}
                </tbody>
              </table>
            </div>
          </div>
        {% endfor %}
      </div>
    {% endif %}
  </div>

  <script>
    function toggleThread(threadId) {
        const threadElement = document.getElementById("thread-" + threadId);
        const toggleIcon = document.getElementById("toggle-icon-" + threadId);
        
        if (threadElement.style.display === "none") {
            threadElement.style.display = "block";
            toggleIcon.innerText = "▲";
        } else {
            threadElement.style.display = "none";
            toggleIcon.innerText = "▼";
        }
    }

    function toggleUploadForm(threadId) {
        const formElement = document.getElementById("upload-form-" + threadId);
        formElement.style.display = formElement.style.display === "none" ? "block" : "none";
    }
  </script>
{% endblock %}