django/chat/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import include, path
from django.utils.html import format_html

from . import responses, views

app_name = "chat"


urlpatterns = [
    path("", views.new_chat, name="new_chat"),
    path("chat-with-ai/", views.new_chat_with_ai, name="chat_with_ai"),
    path("summarize/", views.new_summarize, name="summarize"),
    path("translate/", views.new_translate, name="translate"),
    path("qa/", views.new_qa, name="qa"),
    path("document-qa/", views.new_document_qa, name="document_qa"),
    path("id/<str:chat_id>/", views.chat, name="chat"),
    path("id/<str:chat_id>/upload", views.save_upload, name="upload"),
    path(
        "id/<str:chat_id>/download_glossary/",
        views.download_glossary,
        name="download_glossary",
    ),
    path(
        "id/<str:chat_id>/delete/<str:current_chat>",
        views.delete_chat,
        name="delete_chat",
    ),
    path("delete_all_chats/", views.delete_all_chats, name="delete_all_chats"),
    path("id/<str:chat_id>/message/", views.chat_message, name="chat_message"),
    path(
        "message/<int:message_id>/delete/", views.delete_message, name="delete_message"
    ),
    path(
        "message/<int:message_id>/response/",
        responses.otto_response,
        name="chat_response",
    ),
    path(
        "message/<int:message_id>/response/stop/",
        responses.stop_response,
        name="stop_response",
    ),
    path(
        "message/<int:message_id>/response/cost_warning/",
        views.cost_warning,
        name="cost_warning",
    ),
    path(
        "message/<int:message_id>/sources/",
        views.message_sources,
        name="message_sources",
    ),
    path(
        "message/<int:message_id>/sources/highlight/",
        views.message_sources,  # same view, but highlight will be read from query params
        name="message_sources_highlight",
    ),
    path("file/<int:file_id>/", views.download_file, name="download_file"),
    path(
        "thumbs-feedback/<int:message_id>/<str:feedback>",
        views.thumbs_feedback,
        name="thumbs_feedback",
    ),
    path("id/<str:chat_id>/options/", views.chat_options, name="chat_options"),
    path(
        "id/<str:chat_id>/options/preset/<str:action>",
        views.chat_options,
        name="chat_options",
    ),
    path(
        "id/<str:chat_id>/options/preset/<str:action>/<str:preset_id>",
        views.chat_options,
        name="chat_options",
    ),
    path(
        "id/<str:chat_id>/options/set_qa_library/<int:library_id>",
        views.update_qa_options_from_librarian,
        name="update_from_librarian",
    ),
    path(
        "id/<str:current_chat_id>/rename/<str:chat_id>/",
        views.rename_chat,
        name="rename_chat",
    ),
    path(
        "id/<str:chat_id>/share/",
        views.share_chat,
        name="share_chat",
    ),
    path(
        "id/<str:current_chat_id>/list_item/<str:chat_id>",
        views.chat_list_item,
        name="chat_list_item",
    ),
    path(
        "id/<str:chat_id>/options/presets/",
        views.get_presets,
        name="get_presets",
    ),
    path(
        "id/<str:chat_id>/options/presets/<str:preset_id>/edit/",
        views.edit_preset,
        name="edit_preset",
    ),
    path(
        "id/<str:chat_id>/options/presets/save_options/",
        views.save_preset,
        name="save_preset",
    ),
    path(
        "id/<str:chat_id>/options/presets/form/",
        views.open_preset_form,
        name="open_preset_form",
    ),
    path(
        "presets/<int:preset_id>/default/<str:chat_id>",
        views.set_preset_default,
        name="set_preset_default",
    ),
    path("generate-prompt/", views.generate_prompt_view, name="generate_prompt_view"),
    path("id/<str:chat_id>/email_author/", views.email_author, name="email_author"),
    path(
        "id/<str:current_chat_id>/pin_chat/<str:chat_id>/",
        views.pin_chat,
        name="pin_chat",
    ),
    path(
        "id/<str:current_chat_id>/unpin_chat/<str:chat_id>/",
        views.unpin_chat,
        name="unpin_chat",
    ),
    path("search/", views.search_chats, name="search_chats"),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

django/otto/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import include, path, re_path
from django.views import defaults as default_views

from autocomplete import HTMXAutoComplete
from azure_auth.views import azure_auth_callback

from . import views

urlpatterns = [
    path("healthz/", views.health_check, name="health_check"),
    path("", views.index, name="index"),
    re_path(r"^upload/", include("django_file_form.urls")),
    path("welcome/", views.welcome, name="welcome"),
    # AC-2: Entra Integration Helper App Configuration
    # AC-14: Login Page Accessibility
    path("azure_auth/login", views.login, name="login"),
    path("azure_auth/", include("azure_auth.urls")),
    path("accounts/login/callback/", azure_auth_callback, name="callback"),
    # path("admin/", admin.site.urls), # Do not expose the admin site in production
    path("librarian/", include("librarian.urls")),
    path("laws/", include("laws.urls")),
    path("text_extractor/", include("text_extractor.urls")),
    path("manage_banner/", views.manage_banner, name="manage_banner"),
    path("user_management/", views.manage_users, name="manage_users"),
    path("user_management/form/", views.manage_users_form, name="manage_users_form"),
    path(
        "user_management/form/<user_id>/",
        views.manage_users_form,
        name="manage_users_form",
    ),
    path(
        "user_management/form/<str:user_ids>/",
        views.manage_users_form,
        name="manage_users_form",
    ),
    path("user_management/upload/", views.manage_users_upload, name="upload_users"),
    path(
        "user_management/download/", views.manage_users_download, name="download_users"
    ),
    path("user_management/pilots/", views.manage_pilots, name="manage_pilots"),
    path(
        "user_management/pilots/form/",
        views.manage_pilots_form,
        name="manage_pilots_form",
    ),
    path(
        "user_management/pilots/form/<pilot_id>/",
        views.manage_pilots_form,
        name="manage_pilots_form",
    ),
    path("user_management/costs/", views.cost_dashboard, name="cost_dashboard"),
    path("load_test/enable", views.enable_load_testing, name="enable_load_testing"),
    path("load_test/disable", views.disable_load_testing, name="disable_load_testing"),
    path("load_test/", views.load_test, name="load_test"),
    path("user_cost/", views.user_cost, name="user_cost"),
    path("extend_session/", views.extend_session, name="extend_session"),
    path("terms_of_use/", views.terms_of_use, name="terms_of_use"),
    path(
        "frequently_asked_questions/",
        views.frequently_asked_questions,
        name="frequently_asked_questions",
    ),
    path(
        "user_management/mark_tour_completed/<str:tour_name>/",
        views.mark_tour_completed,
        name="mark_tour_completed",
    ),
    path(
        "user_management/reset_completion_flags/",
        views.reset_completion_flags,
        name="reset_completion_flags",
    ),
    path("feedback/", views.feedback_message, name="user_feedback"),
    path("feedback/<int:message_id>/", views.feedback_message, name="user_feedback"),
    path(
        "user_management/feedback", views.feedback_dashboard, name="feedback_dashboard"
    ),
    path(
        "user_management/feedback/<int:page_number>",
        views.feedback_dashboard,
        name="feedback_dashboard",
    ),
    path("user_management/feedback/list", views.feedback_list, name="feedback_list"),
    path(
        "user_management/feedback/list/<int:page_number>",
        views.feedback_list,
        name="feedback_list",
    ),
    path("user_management/feedback/stats", views.feedback_stats, name="feedback_stats"),
    path(
        "user_management/feedback/<int:feedback_id>/<str:form_type>",
        views.feedback_dashboard_update,
        name="feedback_dashboard_update",
    ),
    path(
        "user_management/feedback/download",
        views.feedback_download,
        name="feedback_download",
    ),
    path("user_management/blocked_urls", views.list_blocked_urls, name="blocked_urls"),
    path(
        "notifications/<int:notification_id>/", views.notification, name="notification"
    ),
    path("notifications/", views.notifications, name="notifications"),
    path("i18n/", include("django.conf.urls.i18n")),
    path("chat/", include("chat.urls")),
    # exposes /metrics endpoint, accessible by anonymous users, restricted by ip addresses. See metrics/web.config and IIS's IP Address and Domain Restrictions
    path("", include("django_prometheus.urls")),
    *HTMXAutoComplete.url_dispatcher("ac"),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if settings.DEBUG_TOOLBAR:
    urlpatterns.append(
        path("__debug__/", include("debug_toolbar.urls")),
    )

if settings.DEBUG:
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page Not Found")},
        ),
        path("500/", default_views.server_error),
    ]

django/template_wizard/urls.py
from template_wizard.views.docx_template import (
    docx_template_status,
    fill_docx_template,
    remove_docx_template,
    upload_docx_template,
)
from template_wizard.views.download_all import download_all_results
from template_wizard.views.fields import delete_field, edit_fields, field_modal
from template_wizard.views.fill_template import (
    fill_template,
    poll_status,
    restart_source_processing,
    source_raw_data,
    source_template_result,
)
from template_wizard.views.layout import edit_layout, test_layout
from template_wizard.views.llm_fields import generate_fields, modify_fields, test_fields
from template_wizard.views.llm_layout import generate_jinja, modify_layout_code
from template_wizard.views.main import (
    delete_session,
    new_session,
    open_session,
    session_history,
    template_list,
    update_pdf_method,
)
from template_wizard.views.sources import (
    add_file_source,
    add_text_source,
    add_url_source,
    delete_all_sources,
    delete_source,
    download_source_file,
    select_sources,
)
from template_wizard.views.template import (
    delete_template,
    edit_example_source,
    edit_metadata,
    new_template,
    update_example_type,
)

app_name = "template_wizard"

from django.urls import path

urlpatterns = [
    path("", template_list, name="index"),
    path("new_template/", new_template, name="new_template"),
    path(
        "edit_template/<int:template_id>/metadata/",
        edit_metadata,
        name="edit_template",
    ),
    path(
        "edit_template/<int:template_id>/metadata/",
        edit_metadata,
        name="edit_metadata",
    ),
    path(
        "edit_template/<int:template_id>/source/",
        edit_example_source,
        name="edit_example_source",
    ),
    path(
        "edit_template/<int:template_id>/fields/",
        edit_fields,
        name="edit_fields",
    ),
    path(
        "edit_template/<int:template_id>/layout/",
        edit_layout,
        name="edit_layout",
    ),
    path(
        "delete_template/<int:template_id>/",
        delete_template,
        name="delete_template",
    ),
    path(
        "edit_template/<int:template_id>/field_modal/",
        field_modal,
        name="field_modal",
    ),
    path(
        "edit_template/<int:template_id>/field_modal/parent/<int:parent_field_id>/",
        field_modal,
        name="field_modal",
    ),
    path(
        "edit_template/<int:template_id>/field_modal/<int:field_id>/",
        field_modal,
        name="field_modal",
    ),
    path(
        "edit_template/<int:template_id>/delete_field/<int:field_id>/",
        delete_field,
        name="delete_field",
    ),
    path(
        "edit_template/<int:template_id>/test_fields/",
        test_fields,
        name="test_fields",
    ),
    path(
        "edit_template/<int:template_id>/test_fields/<int:source_id>/",
        test_fields,
        name="test_fields",
    ),
    path(
        "edit_template/<int:template_id>/test_layout/",
        test_layout,
        name="test_layout",
    ),
    path(
        "edit_template/<int:template_id>/generate_jinja/",
        generate_jinja,
        name="generate_jinja",
    ),
    path(
        "edit_template/<int:template_id>/modify_layout_code/",
        modify_layout_code,
        name="modify_layout_code",
    ),
    path(
        "edit_template/<int:template_id>/generate_fields/<str:from_mode>/",
        generate_fields,
        name="generate_fields",
    ),
    path(
        "edit_template/<int:template_id>/modify_fields/",
        modify_fields,
        name="modify_fields",
    ),
    path(
        "new_session/<int:template_id>/",
        new_session,
        name="new_session",
    ),
    path(
        "session/<int:session_id>/select_sources/",
        select_sources,
        name="select_sources",
    ),
    path(
        "session/<int:session_id>/fill_template/",
        fill_template,
        name="fill_template",
    ),
    path(
        "session/<int:session_id>/add_url_source/",
        add_url_source,
        name="add_url_source",
    ),
    path(
        "source/<int:source_id>/download/",
        download_source_file,
        name="download_source_file",
    ),
    path(
        "source/<int:source_id>/delete/",
        delete_source,
        name="delete_source",
    ),
    path(
        "session/<int:session_id>/delete_all_sources/",
        delete_all_sources,
        name="delete_all_sources",
    ),
    path("session_history/", session_history, name="session_history"),
    path("delete_session/<int:session_id>/", delete_session, name="delete_session"),
    path("open_session/<int:session_id>/", open_session, name="open_session"),
    path(
        "session/<int:session_id>/source/<int:source_id>/raw_data/",
        source_raw_data,
        name="source_raw_data",
    ),
    path(
        "session/<int:session_id>/source/<int:source_id>/template_result/",
        source_template_result,
        name="source_template_result",
    ),
    path(
        "session/<int:session_id>/poll_status/",
        poll_status,
        name="poll_status",
    ),
    path(
        "session/<int:session_id>/source/<int:source_id>/restart_processing/",
        restart_source_processing,
        name="restart_source_processing",
    ),
    path(
        "session/<int:session_id>/download_all/",
        download_all_results,
        name="download_all_results",
    ),
    path(
        "session/<int:session_id>/add_text_source/",
        add_text_source,
        name="add_text_source",
    ),
    path(
        "session/<int:session_id>/add_file_source/",
        add_file_source,
        name="add_file_source",
    ),
    path(
        "update_example_type/<int:source_id>/",
        update_example_type,
        name="update_example_type",
    ),
    path(
        "edit_template/<int:template_id>/upload_docx_template/",
        upload_docx_template,
        name="upload_docx_template",
    ),
    path(
        "edit_template/<int:template_id>/remove_docx_template/",
        remove_docx_template,
        name="remove_docx_template",
    ),
    path(
        "edit_template/<int:template_id>/docx_template_status/",
        docx_template_status,
        name="docx_template_status",
    ),
    path(
        "edit_template/<int:template_id>/fill_docx_template/",
        fill_docx_template,
        name="fill_docx_template",
    ),
    path(
        "update_pdf_method/<int:session_id>/",
        update_pdf_method,
        name="update_pdf_method",
    ),
]

django/template_wizard/templates/template_wizard/edit_template/docx_upload_result_fragment.html
{% load i18n %}
{# HTMX fragment to show the result of the docx template upload #}
{% if template.docx_template %}
  <div class="d-flex justify-content-between align-items-center">
    <div>{% trans "Current template:" %} {{ template.docx_template_filename }}</div>
    <div>
      <form id="remove-docx-template-form"
            hx-post="{% url 'template_wizard:remove_docx_template' template.id %}"
            hx-target="#docx_upload_result"
            hx-swap="innerHTML"
            hx-indicator="#docx-modal-spinner"
            method="post">
        {% csrf_token %}
        <button type="submit" class="btn btn-outline-danger">{% trans "Remove" %}</button>
      </form>
    </div>
  </div>
  {% if docx_validation %}
    <div class="mt-2">
      {% if docx_validation.is_valid %}
        <div class="alert alert-success p-2 mb-1">{% trans "Word template is valid (contains all top-level fields)" %}</div>
      {% else %}
        <div class="alert alert-warning p-2 mb-1">
          {% if docx_validation.error %}
            <div>
              <b>{% trans "Error validating template:" %}</b> {{ docx_validation.error }}
            </div>
          {% endif %}
          {% if docx_validation.missing_fields %}
            <div>
              <b>{% trans "Missing top-level fields:" %}</b> {{ docx_validation.missing_fields|join:", " }}
            </div>
          {% endif %}
          {% if docx_validation.invalid_fields %}
            <div>
              <b>{% trans "Invalid fields found in template:" %}</b> {{ docx_validation.invalid_fields|join:", " }}
            </div>
          {% endif %}
        </div>
      {% endif %}
    </div>
  {% endif %}
{% else %}
  <em>{% trans "No Word template selected." %}</em>
{% endif %}

django/template_wizard/templates/template_wizard/edit_template/field_list.html
{% load i18n %}

<ul class="list-group" aria-label="{% trans 'Fields' %}">
  {% for field in fields %}
    {% if field.parent_field == parent_field %}
      <li class="list-group-item">
        <div class="d-flex align-items-center">
          <div class="flex-grow-1">
            <span class="fw-semibold me-1">{{ field.field_name }}</span>
            <span class="badge bg-secondary">{% trans field.get_field_type_display %}</span>
            {% if field.required %}
              <span class="badge bg-danger">{% trans "Required" %}</span>
            {% endif %}
            {% if field.list %}
              <span class="badge bg-primary">{% trans "List" %}</span>
            {% endif %}
            {% if field.field_type == "str" and field.string_format != "none" %}
              <span class="badge bg-info text-black">{{ field.get_string_format_display }}</span>
            {% endif %}
          </div>
          <div class="ms-2">
            {% if field.field_type == "object" %}
              <button type="button"
                      class="btn px-0 me-2 text-success hover-change-content"
                      data-bs-toggle="modal"
                      data-bs-target="#fieldModal"
                      hx-get="{% url 'template_wizard:field_modal' template_id=template.id parent_field_id=field.id %}"
                      hx-target="#fieldModal .modal-content"
                      hx-swap="innerHTML"
                      onclick="document.querySelector('#fieldModal .modal-content').innerHTML = ''"
                      title="{% trans 'Add child field' %}">
                <span class="non-hover"><i class="bi bi-plus-circle"></i></span>
                <span class="only-hover"><i class="bi bi-plus-circle-fill"></i></span>
                <small class="visually-hidden">{% trans "Add child field" %}</small>
              </button>
            {% endif %}
            <button type="button"
                    class="btn px-0 me-2 text-primary hover-change-content"
                    data-bs-toggle="modal"
                    data-bs-target="#fieldModal"
                    hx-get="{% url 'template_wizard:field_modal' template_id=template.id field_id=field.id %}"
                    hx-target="#fieldModal .modal-content"
                    hx-swap="innerHTML"
                    onclick="document.querySelector('#fieldModal .modal-content').innerHTML = ''"
                    title="{% trans 'Edit' %}">
              <span class="non-hover"><i class="bi bi-pencil"></i></span>
              <span class="only-hover"><i class="bi bi-pencil-fill"></i></span>
              <small class="visually-hidden">{% trans "Edit" %}</small>
            </button>
            <a class="btn px-0 me-0 hover-change-content"
               href="{% url 'template_wizard:delete_field' template_id=template.id field_id=field.id %}"
               onclick="return confirm('{% trans 'Are you sure you want to delete this field?' %}');"
               title="{% trans 'Delete' %}">
              <span class="non-hover"><i class="bi bi-trash text-secondary"></i></span>
              <span class="only-hover"><i class="bi bi-trash-fill text-danger"></i></span>
              <span class="visually-hidden">{% trans "Delete" %}</span>
            </a>
          </div>
        </div>
        {% if field.description %}<div class="text-muted small">{{ field.description }}</div>{% endif %}
        {% if field.field_type == "object" %}
          <div class="mt-2 child-fields-container">
            {% with field as parent_field %}
              {% include "template_wizard/edit_template/field_list.html" with fields=field.child_fields.all %}
            {% endwith %}
          </div>
        {% endif %}
      </li>
    {% endif %}
  {% empty %}
    <li class="list-group-item text-muted">
      <em>{% trans "No fields defined yet." %}</em>
    </li>
  {% endfor %}
</ul>

django/template_wizard/templates/template_wizard/edit_template/fields.html
{% load i18n %}

<div class="row">
  <div class="col-xl-5 border-end">
    <div class="d-flex justify-content-between align-items-center mb-3">
      <h4>{% trans "Fields to extract" %}</h4>
      <div>
        <div class="d-inline-block me-2"
             style="position: relative;
                    top: 10px;
                    margin-top: -10px">
          <div id="generate-fields-spinner" class="spinner text-primary">
            <span class="spinner-border" aria-hidden="true"></span>
            <span class="visually-hidden" role="status">{% trans "Loading" %}</span>
          </div>
        </div>
        {% include "template_wizard/edit_template/field_generate_dropdown.html" with example_template=template.example_template example_sources=template.example_sources %}
        <button type="button"
                class="btn btn-success"
                data-bs-toggle="modal"
                data-bs-target="#fieldModal"
                hx-get="{% url 'template_wizard:field_modal' template_id=template.id %}"
                hx-target="#fieldModal .modal-content"
                hx-swap="innerHTML"
                onclick="document.querySelector('#fieldModal .modal-content').innerHTML = ''">
          {% trans "Add field" %}
        </button>
      </div>
    </div>
    <div class="mb-3" id="field-list">
      {% with template.fields.all as fields %}
        {% include "template_wizard/edit_template/field_list.html" %}
      {% endwith %}
    </div>
    <div class="text-muted small mb-3">
      {% trans "Note: Template name and description also influence the extraction results." %}
    </div>
    <form id="modify-fields-form"
          hx-post="{% url 'template_wizard:modify_fields' template_id=template.id %}"
          hx-target="#field-list"
          hx-swap="innerHTML"
          hx-indicator="#generate-fields-spinner"
          method="post">
      {% csrf_token %}
      <label for="modification_instruction" class="form-label visually-hidden">{% trans "Modify fields using Otto" %}</label>
      <div class="input-group mb-3">
        <input type="text"
               name="modification_instruction"
               id="modification_instruction"
               class="form-control"
               placeholder="{% trans 'Instruct Otto to modify the fields...' %}"
               aria-label="Modification instruction"
               required>
        <button class="btn btn-outline-primary" type="submit">{% trans "Modify fields" %}</button>
      </div>
    </form>
  </div>

  <div class="col-xl-7">
    <div class="d-flex justify-content-between align-items-center mb-3">
      <h4>{% trans "Results on example source" %}</h4>
      <div>
        <div class="d-inline-block me-2"
             style="position: relative;
                    top: 10px;
                    margin-top: -10px">
          <div id="test-fields-spinner" class="spinner text-primary">
            <span class="spinner-border" aria-hidden="true"></span>
            <span class="visually-hidden" role="status">{% trans "Loading" %}</span>
          </div>
        </div>
        {% include "template_wizard/edit_template/test_fields_dropdown.html" %}
      </div>
    </div>
    <div id="test-fields">{% include "template_wizard/edit_template/test_fields_fragment.html" %}</div>
  </div>
</div>

<!-- Modal -->
<div class="modal fade"
     id="fieldModal"
     tabindex="-1"
     aria-labelledby="fieldModalLabel"
     aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <!-- Modal content loaded here by HTMX -->
    </div>
  </div>
</div>

<div class="row mt-3">
  <div class="col text-end">
    <a class="btn btn-primary"
       href="{% url 'template_wizard:edit_layout' template.id %}">
      {% trans "Next" %}<i class="bi bi-chevron-right ms-2"></i>
    </a>
  </div>
</div>

<script>
document.addEventListener('DOMContentLoaded', function() {
  var testBtn = document.querySelector('button[hx-get][hx-target="#test-fields"]');
  if (testBtn) {
    testBtn.addEventListener('click', function(event) {
      if (!document.querySelectorAll('#field-list li button').length) {
        alert("{% trans 'You must add fields before testing extraction.' %}");
        event.preventDefault();
        event.stopImmediatePropagation();
        return false;
      }
    }, true); // useCapture=true
  }

  // Clear the modify fields form after HTMX request
  var modifyForm = document.getElementById('modify-fields-form');
  if (modifyForm) {
    modifyForm.addEventListener('htmx:afterRequest', function(event) {
      modifyForm.reset();
    });
  }
});
</script>

django/template_wizard/templates/template_wizard/edit_template/layout.html
{% load i18n %}

{% include "template_wizard/edit_template/word_template_modal.html" %}

<div class="row">
  <div class="col-lg-5 border-end">
    <div class="d-flex justify-content-between align-items-center mb-3">
      <h4>{% trans "Define template" %}</h4>
      <div>
        <div class="d-inline-block me-2"
             style="position: relative;
                    top: 10px;
                    margin-top: -10px">
          <div id="generate-template-spinner" class="spinner text-primary">
            <span class="spinner-border" aria-hidden="true"></span>
            <span class="visually-hidden" role="status">{% trans "Loading" %}</span>
          </div>
        </div>
        <button type="button"
                class="btn btn-success"
                id="generate-jinja-btn"
                hx-post="{% url 'template_wizard:generate_jinja' template_id=template.id %}"
                hx-target="#layout-form-container"
                hx-swap="innerHTML"
                hx-indicator="#generate-template-spinner">{% trans "Generate layout code" %}</button>
      </div>
    </div>
    <div id="docx_template_status">{% include "template_wizard/edit_template/docx_template_status.html" %}</div>
    <div id="layout-form-container">{% include "template_wizard/edit_template/layout_form.html" %}</div>
  </div>
  <div class="col-lg-7">
    <div class="d-flex justify-content-between align-items-center mb-3">
      <h4>{% trans "Results on example source" %}</h4>
      <div>
        <div class="d-inline-block me-2"
             style="position: relative;
                    top: 10px;
                    margin-top: -10px">
          <div id="test-layout-spinner" class="spinner text-primary">
            <span class="spinner-border" aria-hidden="true"></span>
            <span class="visually-hidden" role="status">{% trans "Loading" %}</span>
          </div>
        </div>
        <button type="button"
                id="test-layout-btn"
                class="btn btn-outline-success"
                hx-get="{% url 'template_wizard:test_layout' template_id=template.id %}"
                hx-target="#test-layout"
                hx-swap="innerHTML"
                hx-indicator="#test-layout-spinner">{% trans "Test layout" %}</button>
      </div>
    </div>
    <div id="test-layout">{% include "template_wizard/edit_template/template_result_fragment.html" %}</div>
  </div>
</div>
<div class="mt-4 d-flex justify-content-end">
  <a href="{% url 'template_wizard:index' %}" class="btn btn-primary">{% trans "Finish" %}</a>
</div>

<script>
document.addEventListener('DOMContentLoaded', function() {
  function hasFields() {
    return {{ template.fields.all|length }} > 0 && {{ template.last_example_source.extracted_json|length }} > 0;
  }
  function blockIfNoFields(event) {
    if (!hasFields()) {
      alert("{% trans 'You must add fields and test extraction before generating a layout' %}");
      event.preventDefault();
      event.stopImmediatePropagation();
      return false;
    }
  }
  var jinjaBtn = document.getElementById('generate-jinja-btn');
  if (jinjaBtn) {
    jinjaBtn.addEventListener('click', blockIfNoFields, true);
  }
});
</script>

django/template_wizard/templates/template_wizard/edit_template/layout_form.html
{% load i18n %}

<form class="g-3"
      id="edit_preset_form"
      hx-post="{% url 'template_wizard:edit_layout' template_id=template.id %}"
      hx-trigger="change delay:300ms"
      hx-swap="none"
      method="post">
  {% csrf_token %}
  <div class="mb-3">
    {{ layout_form.layout_jinja.label_tag }}
    {{ layout_form.layout_jinja }}
    {% if layout_form.layout_jinja.help_text %}
      <div class="form-text">{{ layout_form.layout_jinja.help_text }}</div>
    {% endif %}
  </div>
</form>

{# LLM modify code form #}
<div id="modify-layout-form-container" class="mt-3">
  <form id="modify-layout-form"
        hx-post="{% url 'template_wizard:modify_layout_code' template_id=template.id %}"
        hx-target="#layout-form-container"
        hx-swap="innerHTML"
        hx-indicator="#generate-template-spinner"
        method="post">
    {% csrf_token %}
    <label for="modification_instruction" class="form-label visually-hidden">
      {% trans "Modify layout code using Otto" %}
    </label>
    <div class="input-group mb-3">
      <input type="text"
             name="modification_instruction"
             id="modification_instruction"
             class="form-control"
             placeholder="{% trans 'Instruct Otto to modify the code...' %}"
             aria-label="Modification instruction"
             required>
      <button class="btn btn-outline-primary" type="submit">{% trans "Modify code" %}</button>
    </div>
  </form>
</div>
<script>
document.addEventListener('DOMContentLoaded', function() {
  var modifyLayoutForm = document.getElementById('modify-layout-form');
  if (modifyLayoutForm) {
    modifyLayoutForm.addEventListener('htmx:afterRequest', function(event) {
      modifyLayoutForm.reset();
    });
  }
});
</script>