django/chat/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import include, path
from django.utils.html import format_html

from . import responses, views

app_name = "chat"


urlpatterns = [
    path("", views.new_chat, name="new_chat"),
    path("chat-with-ai/", views.new_chat_with_ai, name="chat_with_ai"),
    path("summarize/", views.new_summarize, name="summarize"),
    path("translate/", views.new_translate, name="translate"),
    path("qa/", views.new_qa, name="qa"),
    path("document-qa/", views.new_document_qa, name="document_qa"),
    path("id/<str:chat_id>/", views.chat, name="chat"),
    path("id/<str:chat_id>/upload", views.save_upload, name="upload"),
    path(
        "id/<str:chat_id>/download_glossary/",
        views.download_glossary,
        name="download_glossary",
    ),
    path(
        "id/<str:chat_id>/delete/<str:current_chat>",
        views.delete_chat,
        name="delete_chat",
    ),
    path("delete_all_chats/", views.delete_all_chats, name="delete_all_chats"),
    path("id/<str:chat_id>/message/", views.chat_message, name="chat_message"),
    path(
        "message/<int:message_id>/delete/", views.delete_message, name="delete_message"
    ),
    path(
        "message/<int:message_id>/response/",
        responses.otto_response,
        name="chat_response",
    ),
    path(
        "message/<int:message_id>/response/stop/",
        responses.stop_response,
        name="stop_response",
    ),
    path(
        "message/<int:message_id>/response/cost_warning/",
        views.cost_warning,
        name="cost_warning",
    ),
    path(
        "message/<int:message_id>/sources/",
        views.message_sources,
        name="message_sources",
    ),
    path(
        "message/<int:message_id>/sources/highlight/",
        views.message_sources,  # same view, but highlight will be read from query params
        name="message_sources_highlight",
    ),
    path("file/<int:file_id>/", views.download_file, name="download_file"),
    path(
        "thumbs-feedback/<int:message_id>/<str:feedback>",
        views.thumbs_feedback,
        name="thumbs_feedback",
    ),
    path("id/<str:chat_id>/options/", views.chat_options, name="chat_options"),
    path(
        "id/<str:chat_id>/options/preset/<str:action>",
        views.chat_options,
        name="chat_options",
    ),
    path(
        "id/<str:chat_id>/options/preset/<str:action>/<str:preset_id>",
        views.chat_options,
        name="chat_options",
    ),
    path(
        "id/<str:chat_id>/options/set_qa_library/<int:library_id>",
        views.update_qa_options_from_librarian,
        name="update_from_librarian",
    ),
    path(
        "id/<str:current_chat_id>/rename/<str:chat_id>/",
        views.rename_chat,
        name="rename_chat",
    ),
    path(
        "id/<str:chat_id>/share/",
        views.share_chat,
        name="share_chat",
    ),
    path(
        "id/<str:current_chat_id>/list_item/<str:chat_id>",
        views.chat_list_item,
        name="chat_list_item",
    ),
    path(
        "id/<str:chat_id>/options/presets/",
        views.get_presets,
        name="get_presets",
    ),
    path(
        "id/<str:chat_id>/options/presets/<str:preset_id>/edit/",
        views.edit_preset,
        name="edit_preset",
    ),
    path(
        "id/<str:chat_id>/options/presets/save_options/",
        views.save_preset,
        name="save_preset",
    ),
    path(
        "id/<str:chat_id>/options/presets/form/",
        views.open_preset_form,
        name="open_preset_form",
    ),
    path(
        "presets/<int:preset_id>/default/<str:chat_id>",
        views.set_preset_default,
        name="set_preset_default",
    ),
    path("generate-prompt/", views.generate_prompt_view, name="generate_prompt_view"),
    path("id/<str:chat_id>/email_author/", views.email_author, name="email_author"),
    path(
        "id/<str:current_chat_id>/pin_chat/<str:chat_id>/",
        views.pin_chat,
        name="pin_chat",
    ),
    path(
        "id/<str:current_chat_id>/unpin_chat/<str:chat_id>/",
        views.unpin_chat,
        name="unpin_chat",
    ),
    path("search/", views.search_chats, name="search_chats"),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

django/otto/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import include, path, re_path
from django.views import defaults as default_views

from autocomplete import HTMXAutoComplete
from azure_auth.views import azure_auth_callback

from . import views

urlpatterns = [
    path("healthz/", views.health_check, name="health_check"),
    path("", views.index, name="index"),
    re_path(r"^upload/", include("django_file_form.urls")),
    path("welcome/", views.welcome, name="welcome"),
    # AC-2: Entra Integration Helper App Configuration
    # AC-14: Login Page Accessibility
    path("azure_auth/login", views.login, name="login"),
    path("azure_auth/", include("azure_auth.urls")),
    path("accounts/login/callback/", azure_auth_callback, name="callback"),
    # path("admin/", admin.site.urls), # Do not expose the admin site in production
    path("librarian/", include("librarian.urls")),
    path("laws/", include("laws.urls")),
    path("text_extractor/", include("text_extractor.urls")),
    path("manage_banner/", views.manage_banner, name="manage_banner"),
    path("user_management/", views.manage_users, name="manage_users"),
    path("user_management/form/", views.manage_users_form, name="manage_users_form"),
    path(
        "user_management/form/<user_id>/",
        views.manage_users_form,
        name="manage_users_form",
    ),
    path(
        "user_management/form/<str:user_ids>/",
        views.manage_users_form,
        name="manage_users_form",
    ),
    path("user_management/upload/", views.manage_users_upload, name="upload_users"),
    path(
        "user_management/download/", views.manage_users_download, name="download_users"
    ),
    path("user_management/pilots/", views.manage_pilots, name="manage_pilots"),
    path(
        "user_management/pilots/form/",
        views.manage_pilots_form,
        name="manage_pilots_form",
    ),
    path(
        "user_management/pilots/form/<pilot_id>/",
        views.manage_pilots_form,
        name="manage_pilots_form",
    ),
    path("user_management/costs/", views.cost_dashboard, name="cost_dashboard"),
    path("load_test/enable", views.enable_load_testing, name="enable_load_testing"),
    path("load_test/disable", views.disable_load_testing, name="disable_load_testing"),
    path("load_test/", views.load_test, name="load_test"),
    path("user_cost/", views.user_cost, name="user_cost"),
    path("extend_session/", views.extend_session, name="extend_session"),
    path("terms_of_use/", views.terms_of_use, name="terms_of_use"),
    path(
        "frequently_asked_questions/",
        views.frequently_asked_questions,
        name="frequently_asked_questions",
    ),
    path(
        "user_management/mark_tour_completed/<str:tour_name>/",
        views.mark_tour_completed,
        name="mark_tour_completed",
    ),
    path(
        "user_management/reset_completion_flags/",
        views.reset_completion_flags,
        name="reset_completion_flags",
    ),
    path("feedback/", views.feedback_message, name="user_feedback"),
    path("feedback/<int:message_id>/", views.feedback_message, name="user_feedback"),
    path(
        "user_management/feedback", views.feedback_dashboard, name="feedback_dashboard"
    ),
    path(
        "user_management/feedback/<int:page_number>",
        views.feedback_dashboard,
        name="feedback_dashboard",
    ),
    path("user_management/feedback/list", views.feedback_list, name="feedback_list"),
    path(
        "user_management/feedback/list/<int:page_number>",
        views.feedback_list,
        name="feedback_list",
    ),
    path("user_management/feedback/stats", views.feedback_stats, name="feedback_stats"),
    path(
        "user_management/feedback/<int:feedback_id>/<str:form_type>",
        views.feedback_dashboard_update,
        name="feedback_dashboard_update",
    ),
    path(
        "user_management/feedback/download",
        views.feedback_download,
        name="feedback_download",
    ),
    path("user_management/blocked_urls", views.list_blocked_urls, name="blocked_urls"),
    path(
        "notifications/<int:notification_id>/", views.notification, name="notification"
    ),
    path("notifications/", views.notifications, name="notifications"),
    path("i18n/", include("django.conf.urls.i18n")),
    path("chat/", include("chat.urls")),
    # exposes /metrics endpoint, accessible by anonymous users, restricted by ip addresses. See metrics/web.config and IIS's IP Address and Domain Restrictions
    path("", include("django_prometheus.urls")),
    *HTMXAutoComplete.url_dispatcher("ac"),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if settings.DEBUG_TOOLBAR:
    urlpatterns.append(
        path("__debug__/", include("debug_toolbar.urls")),
    )

if settings.DEBUG:
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page Not Found")},
        ),
        path("500/", default_views.server_error),
    ]

django/text_extractor/urls.py
from django.urls import path

from . import views

app_name = "text_extractor"

urlpatterns = [
    path("", views.index, name="index"),
    path("submit_document/", views.submit_document, name="submit_document"),
    path(
        "download_document/<str:file_id>/<str:file_type>",
        views.download_document,
        name="download_document",
    ),
    path(
        "download_all_zip/",
        views.download_all_zip,
        name="download_all_zip",
    ),
    path("session/<str:user_request_id>", views.poll_tasks, name="poll_tasks"),
]

django/text_extractor/models.py
# Create your models here.
from django.db import models

from otto.secure_models import SecureModel


class UserRequest(SecureModel):
    name = models.CharField(max_length=255, default="Untitled request")
    created_at = models.DateTimeField(auto_now_add=True)
    merged = models.BooleanField(default=False)

    def __str__(self):
        return f"{self.name} - {self.created_at.strftime('%Y-%m-%d %H:%M:%S')}"


class OutputFile(SecureModel):
    pdf_file = models.FileField(upload_to="ocr_output_files/", blank=True, null=True)
    txt_file = models.FileField(upload_to="ocr_output_files/", blank=True, null=True)
    usd_cost = models.FloatField(default=0.0)
    # Appropriate extension will be appended to the filename when downloaded
    file_name = models.TextField(default="tmp")
    user_request = models.ForeignKey(
        UserRequest, related_name="output_files", on_delete=models.CASCADE
    )
    celery_task_ids = models.JSONField(default=list, blank=True, null=True)
    error_message = models.TextField(blank=True, null=True)

    def get_permission_parents(self):
        return [self.user_request]

django/text_extractor/templates/text_extractor/completed_documents.html
{% load i18n %}

{% for output_file in output_files %}
  <tr>
    <td>
      {# column1: Document #}
      {{ output_file.file_name }}
    </td>
    <td>
      {# column2: Status #}
      {% if output_file.status == "PENDING" %}
        {# Grey circle #}
        <div class="document-status document-status-{{ document.status }}">
          <i class="bi bi-circle text-secondary small me-1" aria-hidden="true"></i>
          <span>{% trans 'Queued' %}...</span>
        </div>
      {% elif output_file.status == "PROCESSING" %}
        {# Blue spinner #}
        <div class="document-status document-status-{{ document.status }}">
          <span class="me-1">
            <i class="bi bi-arrow-repeat text-primary small icn-spinner"
               aria-hidden="true"></i>
          </span>
          <span>
            {% if document.celery_status_message %}
              {{ document.celery_status_message }}
            {% else %}
              {% trans 'Processing' %}...
            {% endif %}
          </span>
        </div>
      {% elif output_file.status == "SUCCESS" %}
        {# Green checkmark #}
        <div class="document-status document-status-{{ document.status }}">
          <i class="bi bi-check-circle-fill text-success small me-1"
             aria-hidden="true"></i>
          <span>{% trans 'Processed' %}</span>
          {% if document.content_type == "application/pdf" %}
            {% if document.pdf_method %}<span class="text-muted">({{ document.pdf_method }})</span>{% endif %}
          {% endif %}
        </div>
      {% elif output_file.status == "FAILURE" %}
        {# Red exclamation mark #}
        <div class="document-status document-status-{{ document.status }}">
          <i class="bi bi-exclamation-circle-fill text-danger small me-1"
             aria-hidden="true"></i>
          <span>
            {% if output_file.error_message %}
              {{ output_file.error_message }}
            {% else %}
              {% trans 'Error' %}
            {% endif %}
          </span>
        </div>
      {% endif %}
    </td>
    <td>
      {# column3: Cost #}
      {{ output_file.cost }}
    </td>
    <td>
      {% if output_file.pdf_file %}
        {# column4: Results #}
        <a href="{% url 'text_extractor:download_document' output_file.id 'pdf' %}"
           class="me-3 text-nowrap icon-link">
          <i class="bi bi-filetype-pdf h5 text-danger"></i>
        PDF ({{ output_file.pdf_size }})</a>
      {% endif %}
      {% if output_file.txt_file %}
        <a href="{% url 'text_extractor:download_document' output_file.id 'txt' %}"
           class="text-nowrap icon-link">
          <i class="bi bi-filetype-txt h5 text-muted"></i>
        {% trans "Plain text" %} ({{ output_file.txt_size }})</a>
      {% endif %}
    </td>
  </tr>
{% endfor %}
{% if poll_url %}
  <tr class="d-none"
      id="poller"
      hx-get="{{ poll_url }}"
      hx-trigger="load delay:1s"
      hx-swap="innerHTML"
      hx-target="#completed_documents_body"></tr>
  {% if swap %}
    {% include 'text_extractor/warn_dont_leave.html' %}
  {% endif %}
{% elif swap %}
  <div id="warn-dont-leave-page" hx-swap-oob="true" class="d-none"></div>
{% endif %}

{# OOB update to toggle the header "Download all" button #}
{% if swap and show_download_all_button %}
  {% include "text_extractor/download_all_button.html" %}
{% endif %}

{% if user_request_id %}
  <script>window.location.href = "{% url 'text_extractor:poll_tasks' user_request_id=user_request_id %}";</script>
{% endif %}
<script>
(function () {
  // If arriving at a page fragment via browser back-forward, refresh.
  // A page fragment will not have the #top-nav element
  let is_page_fragment = document.getElementById('top-nav') === null;
  if (performance.navigation.type === 2 && is_page_fragment) {
    location.reload();
  }
})();
</script>

django/text_extractor/templates/text_extractor/download_all_button.html
{% load i18n %}
<span id="download-all-files-button"
      class="ms-auto"
      {% if swap %}hx-swap-oob="true"{% endif %}>
  {% if show_download_all_button %}
    <a href="{% url 'text_extractor:download_all_zip' %}"
       class="btn btn-sm p-0 m-0 text-decoration-none ms-auto"
       title="{% trans 'Download all files' %}"
       aria-label="{% trans 'Download all files' %}"
       id="download-all-files-button">
      <i class="bi bi-download align-baseline"></i> ZIP
    </a>
  {% endif %}
</span>

django/text_extractor/templates/text_extractor/error_message.html
{% load i18n %}

<div id="error_message"
     class="my-4 alert alert-danger"
     role="alert"
     hx-swap-oob="true"
     style="max-width: 500px;
            margin: 0 auto">
  {% if error_message %}
    {{ error_message }}
  {% else %}
    {% trans "Sorry, we ran into an error. Error ID: %(error_id)s." %}
  {% endif %}
</div>
<script>
  document.getElementById('merge_documents').classList.add('d-none');
  document.getElementById('file-upload-field').value = '';
  document.getElementById('merge_docs_checkbox').checked = false;
</script>

django/text_extractor/templates/text_extractor/ocr.html
{% extends 'base.html' %}
{% load static %}
{% load i18n %}

{% block page_title %}
  {% trans "Text Extractor - Otto" %}
{% endblock %}

{% block page_css %}
  <link rel="stylesheet" href="{% static 'text_extractor/style.css' %}">
{% endblock %}

{% block content_container %}
  <div class="container py-3 px-0">
    <h2 class="my-2 px-4">
      <a href="{% url 'text_extractor:index' %}"
         class="text-decoration-none text-body">{% trans "Text Extractor" %}</a>
    </h2>
    <p class="mb-4 mx-4">{% trans "Extract text and handwriting from scanned PDF and images with AI-enabled OCR." %}</p>
    <div class="card">
      <div class="card-body p-4">
        <form method="post"
              enctype="multipart/form-data"
              hx-post="{% url 'text_extractor:submit_document' %}"
              hx-target="#completed_documents_body"
              hx-swap="innerHTML"
              id="submit_document_form"
              hx-indicator="#spinner"
              onsubmit="document.getElementById('submit').disabled = true;">
          {% csrf_token %}
          <h3 class="h4" id="upload-label">{% trans "Upload scanned PDFs or images" %}</h3>
          <p class="text-secondary mb-4">{% trans "Maximum 2000 files / 300MB total" %}</p>
          <div class="mb-4">
            <input class="form-control"
                   id="file-upload-field"
                   name="file_upload"
                   type="file"
                   accept="{{ extensions }}"
                   hx-trigger="change"
                   hx-select="#submit"
                   aria-labelledby="upload-label"
                   multiple>
            <div class="form-check d-none mt-3" id="merge_documents">
              <input class="form-check-input border-secondary"
                     type="checkbox"
                     name="merge_docs_checkbox"
                     id="merge_docs_checkbox">
              <label class="form-check-label" for="merge_docs_checkbox">{% trans "Merge multiple files into one document" %}</label>
            </div>
          </div>
          <div class="row mb-1">
            <div class="col-auto">
              <button type="submit" class="btn btn-primary" id="submit" disabled="">{% trans "Submit" %}</button>
            </div>
            <div class="col" style="margin-top:2px;">
              <div class="spinner text-primary" role="status" id="spinner">
                <span class="visually-hidden">Loading...</span>
                <span class="spinner-border" aria-hidden="true"></span>
              </div>
            </div>
          </div>
        </form>
      </div>
    </div>

    <div id="error_message" role="alert"></div>

    <div id="completed-documents">
      {% if not show_output %}
        {# Initial warning message - cleared when form submitted #}
        {% include "text_extractor/ocr_warning.html" %}
      {% endif %}
      <div class="card mt-4 {% if not show_output %}d-none{% endif %}"
           aria-live="polite"
           aria-atomic="true">
        <div class="card-body p-4">
          <div>
            {# "Completed documents" also includes in-progress now that we're using celery #}
            <h3 class="h4 mb-3">{% trans "Output documents" %}</h3>
            {% if poll_url %}
              {% include 'text_extractor/warn_dont_leave.html' %}
            {% else %}
              <div id="warn-dont-leave-page" class="d-none"></div>
            {% endif %}
            <table class="table">
              <thead>
                <tr>
                  <th scope="col" width="50%">{% trans "Document name" %}</th>
                  <th scope="col" width="20%">{% trans "Status" %}</th>
                  <th scope="col" width="10%">{% trans "Cost" %}</th>
                  <th scope="col" width="20%">
                    <div class="d-flex justify-content-between align-items-center">
                      <span>{% trans "Downloads" %}</span>
                      {% include "text_extractor/download_all_button.html" %}
                    </div>
                  </th>
                </tr>
              </thead>
              <tbody id="completed_documents_body">
                {% include 'text_extractor/completed_documents.html' %}
              </tbody>
            </table>
          </div>
        </div>
      </div>

    </div>
  </div>
  <script>
  
// event listener for when the documents are completed the spinner is hidden and file input is cleared
document.getElementById('completed_documents_body').addEventListener('htmx:afterSwap', function() {
  document.getElementById('file-upload-field').value = '';
  document.getElementById('merge_documents').classList.add('d-none');
  document.getElementById('completed-documents').classList.remove('d-none');
});

// event listener to enable submit button once files has been uploaded
document.getElementById('file-upload-field').addEventListener('change', function() {
  document.getElementById('submit').disabled = false;
  document.getElementById('merge_docs_checkbox').checked = false;
  
  // if more than one documents are uploaded show the merge documents checkbox
  if (this.files.length > 1) {
    document.getElementById('merge_documents').classList.remove('d-none');
  } else {
    document.getElementById('merge_documents').classList.add('d-none');
  }

  // make sure the error button is removed
  document.getElementById('error_message').classList.add('d-none');
});


{% if not show_output %}
  setTimeout(() => {
    document.querySelector('#file-upload-field').focus();
  }, 100);
{% endif %}
  </script>
{% endblock %}

django/text_extractor/templates/text_extractor/ocr_warning.html
{% load i18n %}
<div class="alert alert-warning my-4 mx-3" role="alert" id="ocr-warning">
  <div class="row">
    <div class="col-auto pe-0">
      <svg class="flex-shrink-0 bi me-2"
           width="24"
           height="24"
           role="img"
           aria-label='{% trans "Warning" %}:'>
        <use xlink:href="#exclamation-triangle-fill"></use>
      </svg>
    </div>
    <div class="col ps-1">
      <h5 class="text-align-center mb-3">{% trans "Safe use of Text Extractor" %}</h5>
    </div>
  </div>
  <div class="row">
    {% if environment == "prod" %}
      <p>
        <strong class="fw-semibold">{% trans "Protected B approved:" %}</strong>
        {% trans "Use with unclassified, Protected A or" %}
        <abbr title="{% trans 'Specific legislation may impose additional requirements pertaining to certain classes of sensitive information that are considered Protected B. In such cases, the use of Otto should be considered on a case-by-case basis.' %}">{% trans "Protected B" %}</abbr>
        {% trans "information only." %}
      </p>
    {% else %}
      <p>
        <strong class="fw-semibold">{% trans "Unclassified only:" %}</strong>
        {% trans "This is a development / testing environment. Use unclassified information only." %}
      </p>
    {% endif %}
    <p class="mb-0">
      <strong class="fw-semibold">{% trans "Human review required:" %}</strong>
      {% trans "AI can make mistakes. Verify the output if you intend to rely upon it." %}
    </p>
  </div>
</div>

django/text_extractor/templates/text_extractor/warn_dont_leave.html
{% load i18n %}

<div id="warn-dont-leave-page"
     {% if swap %}hx-swap-oob="true"{% endif %}
     class="alert alert-info"
     role="alert">
  {% trans "Extraction in progress." %}
  <span class="fw-semibold">{% trans "Please do not leave this page." %}</span>
</div>